version: "3.1"

services:
  db:
    container_name: servidor_mysql
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: bookmedik
      MYSQL_USER: bookmedik
      MYSQL_PASSWORD: bookmedik
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /opt/mysql_wp:/var/lib/mysql

  bookmedik:
     container_name: bookmedik
     image: franmadu6/bookmedik:v2
     restart: always
     environment:
       USER: bookmedik
       PASSWORD: bookmedik
       HOST: db
     ports:
         - 8080:80
     volumes:
         - /opt/bookmedik_logs:/var/log/apache2
